### ISSUE TITLE
Closing parenthesis isn't parsed

### ISSUE THREAD

**Issue by john-cj** [UziTech/hyperlink-hyperclick#10]
Well, another bug report.

```
https://en.wikipedia.org/wiki/Shell_(computing)
```

will be clicked as

```
https://en.wikipedia.org/wiki/Shell_(computing
```

![image](https://user-images.githubusercontent.com/18004961/51795381-63676200-21f3-11e9-983b-dafc004e61f0.png)

**Comment by UziTech** [comment]
This seems to be an issue with https://github.com/atom/language-hyperlink/pull/13
