### ISSUE TITLE
support for weird protocols

### ISSUE THREAD

**Issue by UziTech** [UziTech/hyperlink-hyperclick#6]
right now only works with [language-hyperlink](https://github.com/atom/language-hyperlink) valid protocols because it uses `tokenForBufferPosition`

`<test://test.com>` won't work because the token value will be `"<test://test.com>"` instead of `"test://test.com"`

could use [`textEditor.lineTextForBufferRow(bufferRow)`](https://atom.io/docs/api/v1.7.1/TextEditor#instance-lineTextForBufferRow) and a regexp

**Comment by UziTech** [comment]
here is [language-hyperlinks regexp](https://github.com/atom/language-hyperlink/blob/master/grammars/hyperlink.cson) 

`'(?x)( (https?|s?ftp|ftps|file|smb|afp|nfs|(x-)?man(-page)?|gopher|txmt|issue)://|mailto:)((?!(\\#[a-zA-Z0-9]*\\#))(?:[-:@a-zA-Z0-9.,~%+_\/?=&#;|!]))+(?<![-.,?:#;])'`

**Comment by UziTech** [comment]
or maybe create a grammer?

**Comment by black-snow** [comment]
@UziTech is there anything I can help you with?

**Comment by UziTech** [comment]
This issue would only affect people trying to use unusual protocols.

I'm not sure this is an actual issue. I figured I would put this out there and if people were actually running into this issue I would fix it but so far this doesn't seem to affect anybody.
