### ISSUE TITLE
Set priority to avoid interference w/ other hyperclick plugins

### ISSUE THREAD

**Issue by black-snow** [UziTech/hyperlink-hyperclick#7]
Imo `hyperclick` should set a priority greater than 0 (for it's protocols) to take precedence over other hyperlink plugins (such as goto-definition).
See https://github.com/faceair/atom-goto-definition/issues/49 for more details.

**Comment by black-snow** [comment]
See https://github.com/UziTech/hyperlink-hyperclick/pull/8

**Comment by black-snow** [comment]
#8 merged

**Comment by UziTech** [comment]
I added a setting to be able to set the priority. It is defaulted to 0 so it won't change previous behavior.

**Comment by black-snow** [comment]
@UziTech just got the update, set priority to 1, works fine :)
