### ISSUE TITLE
Colon at the end of hyperlink is treated as it's part

### ISSUE THREAD

**Issue by john-cj** [UziTech/hyperlink-hyperclick#9]
Real-life example: unordered list of Atom packages, where the link is followed by colon and hashtags.

```
* https://atom.io/packages/autocomplete-asciidoc: #asciidoctor, #autocomplere
```

The link will be parsed and clicked with colon (and the page will not be found for this reason). Is it an issue of hyperlink-hyperclick package or Atom itself?

**Comment by UziTech** [comment]
a colon is a valid url character:
https://github.com/atom/language-hyperlink/blob/master/grammars/hyperlink.cson#L5

You can fix this by adding a space before the colon.

**Comment by john-cj** [comment]
Well, in this case it should closed.
