### ISSUE TITLE
Not working maybe due to keybinding conflict

### ISSUE THREAD

**Issue by gabaozin** [UziTech/hyperlink-hyperclick#93]
Hello, could you specify the exact command action so I could add it to my keymay.cson file?

Thank you.

**Comment by UziTech** [comment]
This package uses [hyperclick](https://github.com/facebookarchive/atom-ide-ui/tree/master/modules/atom-ide-ui/pkg/hyperclick) which sets the keys.

If you have a hyperclick service package installed you can see which keys to use in that package.

If you do not have a hyperclick package installed you will have to install one like [hyperclick](https://atom.io/packages/hyperclick) or [atom-ide-ui](https://atom.io/packages/atom-ide-ui)

**Comment by UziTech** [comment]
@gabaozin did you get it working?
